-- Cabecera de tramites (OCRRII)
CREATE TABLE E05MTRM (
   cIdPago CHARACTER(6)   NOT NULL PRIMARY KEY,
   cEstado CHARACTER(1)   NOT NULL,   -- [???] A: PENDIENTE, B: APROBADO, O: OBSERVADO, X: ANULADO
   cDescri VARCHAR(400)   NOT NULL,
   cTipo   CHARACTER(1)   NOT NULL,   -- [???] F: FAMILIAS ANFITRIONAS, T: TOEFL ITP
   dGenera DATE           NOT NULL,
   nMonIng NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
   nMonto  NUMERIC(12, 2) NOT NULL,
   dAproba DATE,
   mObserv TEXT           NOT NULL DEFAULT '',
   cCodApr CHARACTER(4)   NOT NULL DEFAULT '0000' REFERENCES S01TUSU (cCodUsu) ON UPDATE CASCADE ON DELETE RESTRICT,
   cUsuCod CHARACTER(4)   NOT NULL,
   tModifi TIMESTAMP      NOT NULL DEFAULT NOW()
);

-- Detalle de tramites (OCRRII)
CREATE TABLE E05DTRM (
   nSerial SERIAL         NOT NULL UNIQUE,
   cIdPago CHARACTER(6)   NOT NULL REFERENCES E05MTRM (cIdPago) ON UPDATE CASCADE ON DELETE RESTRICT,
   cNroRuc CHARACTER(11)  NOT NULL REFERENCES S01MPRV (cNroRuc) ON UPDATE CASCADE ON DELETE RESTRICT,
   cPeriod CHARACTER(6)   NOT NULL,
   cTipDoc CHARACTER(2)   NOT NULL,   -- [???] Tipo documento comprobante
   cNroDoc CHARACTER(20   NOT NULL,
   cEstado CHARACTER(1)   NOT NULL,   -- [???] R: REGISTRADO, T: TESORERIA, X: ANULADO
   cGlosa  VARCHAR(100)   NOT NULL,
   cMoneda CHARACTER(1)   NOT NULL,   -- [007]
   nMonto  NUMERIC(12, 2) NOT NULL,
   cCodTrx CHARACTER(6)   NOT NULL DEFAULT '000000' REFERENCES D02MTRX (cCodTrx) ON UPDATE CASCADE ON DELETE RESTRICT,
   cUsuCod CHARACTER(4)   NOT NULL,
   tModifi TIMESTAMP      NOT NULL DEFAULT NOW()
);
